### ISSUE TITLE
How to identify/detect a Rover?

### ISSUE THREAD

**Issue by RaphaelBunck** [RescueOnWheels/Cockpit#8]
IP is now hard-coded, we need to figure out how to do this more elegantly

**Comment by RaphaelBunck** [comment]
Mabye a ping-system that lets everybody in the network know who the PI is, listen for that ping on controller and  connect to that device?

I'm bumping the estimate to 3 hrs

**Comment by mvegter** [comment]
Temporary solution would be asking the operator to enter the IP-address that is on the screen of the specific Rover.

**Comment by noxi333** [comment]
Send IP over bluetooth (connections will be remembered).

**Comment by mvegter** [comment]
One central system (socket.io server) to which all clients (rovers and cockpits) connect to. In this central system one person/entity should/could be able to combine two, different, clients (rover and a cockpit) with each other. Sending an object containing the IP-adres which in turn can be used to directly connect to each other.

**Comment by RaphaelBunck** [comment]
## Thoughts:
Let the PI send a packet broadcast to every device on the network. Only the socket client will listen to that broadcast so it knows the PI's IP. Then the client would send a packet back to the socket server (PI) and they would then establish a connection.
